_base_: default.yml
model:
  clip_model_name: ViT-B/16
  keep_cls: false
  keep_end_seq: false
  model_name: dinov2_vitb14_reg
  proj_model: DINOJSCC_Adapter
  proj_name: vitb_jscc_infonce
  proj_class: vitb_jscc_infonce
  resize_dim: 518
  type: DINOJSCC
  use_avg_text_token: false
  k: 256
  text_adapter_pretrain: "weights/vitb_mlp_infonce.pth"